---
title: "Markum_MSDS6306_W5Homework"
author: "AMarkum"
date: "2/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Markum MSDS 6306 Week 5 Homework

## Stored at https://github.com/markumae/SMU_Data

### 1.	Data Munging (30 points): Utilize yob2016.txt for this question. This file is a series of popular children’s names born in the year 2016 in the United States.  It consists of three columns with a first name, a gender, and the amount of children given that name.  However, the data is raw and will need cleaning to make it tidy and usable.
###a.	First, import the .txt file into R so you can process it.  Keep in mind this is not a CSV file.  You might have to open the file to see what you’re dealing with.  Assign the resulting data frame to an object, df, that consists of three columns with human-readable column names for each.
###b.	Display the summary and structure of df
###c.	Your client tells you that there is a problem with the raw file.  One name was entered twice and misspelled.  The client cannot remember which name it is; there are thousands he saw! But he did mention he accidentally put three y’s at the end of the name.  Write an R command to figure out which name it is and display it.
###d.	Upon finding the misspelled name, please remove this particular observation, as the client says it’s redundant.  Save the remaining dataset as an object: y2016 

###PopularNames <- read.table("yob2016.txt", header=TRUE, sep=";")
###colnames(PopularNames) <- c("Name", "Gender", "Rank")
###str(PopularNames)
###dim(PopularNames)

###> str(PopularNames)
###'data.frame':	32868 obs. of  3 variables:
### $ Name  : Factor w/ 30295 levels "Aaban","Aabha",..: 22546 3770 26409 12019 20596 6185 339 9298 11222 2066 ...
### $ Gender: Factor w/ 2 levels "F","M": 1 1 1 1 1 1 1 1 1 1 ...
### $ Rank  : int  19246 16237 16070 14722 14366 13030 11699 10926 10733 10702 ...
###> dim(PopularNames)
###[1] 32868     3

###PopularNames[211, ]
###PopularNames<- PopularNames[-c(211), ]
###y2016 <- PopularNames

###> PopularNames[211, ]
###        Name Gender Rank
###211 Fionayyy      F 1547
###> PopularNames<- PopularNames[-c(211), ]
###> y2016 <- PopularNames
###>

###2.	Data Merging (30 points): Utilize yob2015.txt for this question.  This file is similar to yob2016, but contains names, gender, and total children given that name for the year 2015.
###a.	Like 1a, please import the .txt file into R.  Look at the file before you do.  You might have to change some options to import it properly.  Again, please give the dataframe human-readable column names.  Assign the dataframe to y2015.  

###df <- read.table("yob2015.txt", header = FALSE, sep= ",")
###colnames(df) <- c("Name", "Gender", "Rank")
###str(df)
###dim(df)
###y2015 <- df

###> str(df)
###'data.frame':	33063 obs. of  3 variables:
### $ Name  : Factor w/ 30553 levels "Aaban","Aabha",..: 9474 22858 26680 3771 12170 20927 344 9453 6252 11404 ...
### $ Gender: Factor w/ 2 levels "F","M": 1 1 1 1 1 1 1 1 1 1 ...
### $ Rank  : int  20415 19638 17381 16340 15574 14871 12371 11766 11381 10283 ...
###> dim(df)
###[1] 33063     3
###> y2015 <- df
###b.	Display the last ten rows in the dataframe.  Describe something you find interesting about these 10 rows. This table has been arranged alphabetically within Ranks.

###> tail(y2015, 10)
###        Name Gender Rank
###33054   Ziyu      M    5
###33055   Zoel      M    5
###33056  Zohar      M    5
###33057 Zolton      M    5
###33058   Zyah      M    5
###33059 Zykell      M    5
###33060 Zyking      M    5
###33061  Zykir      M    5
###33062  Zyrus      M    5
###33063   Zyus      M    5
###>
###c.	Merge y2016 and y2015 by your Name column; assign it to final.  The client only cares about names that have data for both 2016 and 2015; there should be no NA values in either of your amount of children rows after merging.

###Final <- merge(y2015,y2016,by="Gender")
###Final <- rbind(y2015, y2016)
###str(Final)
###dim(Final)
###> Final <- merge(y2015,y2016,by="Gender")
###Error: vector memory exhausted (limit reached?)
###> Final <- rbind(y2015, y2016)
###> str(Final)
###'data.frame':	65930 obs. of  3 variables:
### $ Name  : Factor w/ 36212 levels "Aaban","Aabha",..: 9474 22858 26680 3771 12170 20927 344 9453 6252 11404 ...
### $ Gender: Factor w/ 2 levels "F","M": 1 1 1 1 1 1 1 1 1 1 ...
### $ Rank  : int  20415 19638 17381 16340 15574 14871 12371 11766 11381 10283 ...
###> dim(Final)
###[1] 65930     3
###>

###3.	Data Summary (30 points): Utilize your data frame object final for this part.
###a.	Create a new column called “Total” in final that adds the amount of children in 2015 and 2016 together.  In those two years combined, how many people were given popular names?
###b.	Sort the data by Total.  What are the top 10 most popular names?
###c.	The client is expecting a girl!  Omit boys and give the top 10 most popular girl’s names.
###d.	Write these top 10 girl names and their Totals to a CSV file.  Leave out the other columns entirely.
###4.	Upload to GitHub (10 points): Push at minimum your RMarkdown for this homework assignment and a Codebook to one of your GitHub repositories (you might place this in a Homework repo like last week).  The Codebook should contain a short definition of each object you create, and if creating multiple files, which file it is contained in.  You are welcome and encouraged to add other files—just make sure you have a description and directions that are helpful for the grader.



